### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by Bonarieta** [athrvvvv/AppOpener#10]
LOADING APPS... (JUST ONCE)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python39\lib\threading.py", line 950, in _bootstrap_inner
    self.run()
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python39\lib\threading.py", line 888, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 1475, in _readerthread
    buffer.append(fh.read())
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python39\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x94 in position 3381: invalid start byte
Traceback (most recent call last):
  File "c:\Users\ACER\Documents\GitHub\Ami\dfgsdg.py", line 1, in <module>
    from AppOpener import open
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python39\lib\site-packages\AppOpener\__init__.py", line 7, in <module>
    check.check_json()
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python39\lib\site-packages\AppOpener\check.py", line 63, in check_json
    create_file()
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python39\lib\site-packages\AppOpener\check.py", line 52, in create_file
    result = subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, universal_newlines=True, encoding='utf-8')
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 503, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 1130, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 1525, in _communicate
    stdout = stdout[0]
IndexError: list index out of range

**Comment by athrvvvv** [comment]
Hey dude, did you fixed your issue?

**Comment by Bonarieta** [comment]
> Hey dude, did you fixed your issue?

Unfortunately, no

**Comment by athrvvvv** [comment]
Do you have any of Idea...  what is going wrong?

Also tell your Windows Version and In what language you are usig it.

**Comment by Bonarieta** [comment]
I was coding a personal assistant and used AppOpener in a function and it was working fine. when I first built it. But after some time ( I coded too many things after coding it) I noticed that it is not working properly.  The problem is about importing AppOpener. I uninstalled it and then installed it again and again bu still gives the same error. When I type "import AppOpener" at the beginning of the file. Whole file doesn't work. But if I type "import AppOpener" inside the function, that function doesn't work. I am using Python and Windows 10.

**Comment by athrvvvv** [comment]
Okay, do following things.... If these does'nt work I will take care

1. Open CMD
2. Uninstall and Re-Install AppOpener
3. Close CMD
4. Open CMD again
5. Open python there and import AppOpener there and tell me whats happening.....

**Comment by athrvvvv** [comment]
@Bonarieta you dead bro.?.?

**Comment by athrvvvv** [comment]
@Bonarieta Dude, Actually **Iam working on this Issue**. Can you just install: 
```
pip install AppOpener==1.3 
```
And Tell whether the issue still exists. 

Awaiting for you answer,
athrv.

**Comment by athrvvvv** [comment]
**AppOpener v1.7** just released!! ✌️

Install **AppOpener v1.7**:
``` cmd
pip install AppOpener==1.7
```
I have added an Exception, if the **File creation process** failed, it will create files using the old method in AppOpener v1.3
Hope soo, this works!! **If your Issue is fixed, you may close this now** 😊

Lots of love,
athrv ❤️
